# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b74c557b1413c824e54d3053934d404197d5c42dab127b25e51b4bf842a5614a4c96a2bdcf01076d9cbe589c462b6a5210976d164fa51316a3290990edab163

test:
  secret_key_base: 86d4da3e52376c9796e68764f32bb0887167eb1a6adf35d07ea7ee3706c5866c49bdb11479fa3fcf43160ee08c8a91ebab01957ed1e383747bd011ed63e6612d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
